In [1]:
import sqlalchemy
import pandas as pd
from sqlalchemy import create_engine
from credentials import username
from credentials import password
from  psycopg2 import connect

In [44]:
import_ = 'Resources/usretechnicalpotential(clean).csv'
import_2='Resources/energy_consumption.csv'
df = pd.read_csv(import_)
renewabledf= df.set_index('State')
renewable_sum=renewabledf.sum(axis=1)
renewabledf=pd.DataFrame(renewable_sum)
renewabledf=renewabledf.rename(columns={0:'Total Renewable'})
energydf=df.merge(renewabledf,on='State')
energydf

,State,Urban_Solar,Rural_Solar,Rooftop_Solar,CSP_Solar,Onshore_Wind,Offshore_Wind,Biopower_Solid,Biopower_Gaseous,Geothermal_Hydrothermal,EGS_Geothermal,Hydropower,Total Renewable
0,Alabama,35850,3706838,15475.0,0,283,0.0,11193,1533,0,535489.0,4102,4310763.0
1,Alaska,166,8282976,0.0,0,1373433,0.0,513,61,15437,0.0,23675,9696261.0
2,Arizona,121305,11867693,22736.0,12544333,26036,0.0,1087,837,8329,1239147.0,1303,25832806.0
3,Arkansas,28960,4986388,8484.0,0,22892,0.0,14381,1063,0,628621.0,6093,5696882.0
4,California,246008,8855917,106411.0,8490916,89862,2662579.0,12408,15510,130921,1344179.0,30023,21984734.0
5,Colorado,43470,10238083,16162.0,9154524,1096035,0.0,2913,1224,8953,1251657.0,7789,21820810.0
6,Connecticut,7716,19627,6616.0,0,61,26545.0,494,414,0,56078.0,922,118473.0
7,Delaware,14856,272332,2185.0,0,21,60654.0,512,385,0,22813.0,30,373788.0
8,District of Columbia,8,0,2490.0,0,0,0.0,61,4,0,697.0,0,3260.0
9,Florida,72787,5137346,63986.0,358,0,34684.0,9664,3693,0,374161.0,682,5697361.0
10,Georgia,43166,5492183,31116.0,0,322,220807.0,14682,2220,0,353206.0,1988,6159690.0
11,Hawaii,3725,38032,0.0,15369,7786,2836735.0,524,200,20632,0.0,2602,2925605.0
12,Idaho,23194,3936847,4051.0,3502877,44319,0.0,5775,182,17205,993257.0,18757,8546464.0
13,Illinois,103551,8090985,30086.0,0,649467,66070.0,27738,4222,0,676055.0,4882,9653056.0
14,Indiana,98815,4876185,17151.0,0,377603,165.0,14941,2978,0,434258.0,2394,5824490.0
15,Iowa,27091,6994159,8646.0,0,1723587,0.0,27502,1425,0,606390.0,2818,9391618.0
16,Kansas,31705,14500149,8962.0,7974255,3101575,0.0,12104,753,0,989675.0,2507,26621685.0
17,Kentucky,26514,1823976,12312.0,0,147,0.0,7048,1273,0,484658.0,4255,2360183.0
18,Louisiana,55669,4114605,14368.0,0,934,1200698.0,14016,857,0,484271.0,2423,5887841.0
19,Maine,3216,1100327,2443.0,0,28742,631960.0,4273,124,0,377075.0,3916,2152076.0
20,Maryland,28551,585949,14849.0,0,3631,200852.0,2102,1226,0,86649.0,814,924623.0
21,Massachusetts,17469,82204,11722.0,0,2827,799344.0,1045,1103,0,92227.0,1196,1009137.0
22,Michigan,50845,5215639,23527.0,0,143907,1739800.0,9358,2539,0,457850.0,1180,7644645.0
23,Minnesota,33370,10792814,14321.0,0,1428524,100454.0,20361,1029,0,369784.0,1254,12761911.0
24,Mississippi,26366,4981252,8614.0,0,0,10172.0,14209,1076,0,559056.0,2211,5602956.0
25,Missouri,30549,5335268,16159.0,0,689519,0.0,11837,2147,0,835444.0,7198,6928121.0
26,Montana,11370,8187341,2194.0,1540287,2746271,0.0,4924,147,6547,1647303.0,14546,14160930.0
27,Nebraska,12954,9266756,5336.0,4846929,3011252,0.0,16271,750,0,927996.0,3142,18091386.0
28,Nevada,24893,8614454,10767.0,8295752,17709,0.0,288,325,45320,1262174.0,845,18272527.0
29,New Hampshire,3790,57363,2298.0,0,5706,14477.0,953,389,0,104314.0,1740,191030.0
30,New Jersey,44307,439773,15767.0,0,317,429807.0,1212,2310,0,35230.0,549,969272.0
31,New Mexico,71356,16318543,6513.0,16812349,1399156,0.0,595,353,12933,1417978.0,1362,36041138.0
32,New York,52803,1492566,28779.0,0,63565,614279.0,5558,2950,0,375400.0,6711,2642611.0
33,North Carolina,68346,4232789,28419.0,0,2037,1269626.0,12869,3780,0,420741.0,3036,6041643.0
34,North Dakota,4871,9734447,1916.0,36049,2537824,0.0,8186,30,0,820226.0,347,13143896.0
35,Ohio,86495,3626181,30064.0,0,129142,170561.0,11009,3363,0,495921.0,3045,4555781.0
36,Oklahoma,50040,9341920,12442.0,5068036,1521651,0.0,4128,965,0,779667.0,3015,16781864.0
37,Oregon,25783,3740478,8322.0,2812126,68766,962722.0,13793,890,18199,914105.0,18184,8583368.0
38,Pennsylvania,56161,553356,22215.0,0,8230,23571.0,6313,7132,0,327340.0,8368,1012686.0
39,Rhode Island,1787,13636,1710.0,0,129,89114.0,143,474,0,11491.0,59,118543.0
40,South Carolina,33834,2754973,14412.0,0,427,542218.0,6984,1430,0,364104.0,1888,3720270.0
41,South Dakota,4573,10008873,2082.0,1629659,2901858,0.0,8380,235,0,921972.0,1047,15478679.0
42,Tennessee,50243,2225989,19685.0,0,765,0.0,6095,1984,0,428380.0,5744,2738885.0
43,Texas,294684,38993581,78716.0,22786749,5552399,1101062.0,16077,5898,0,3030250.0,3006,71862422.0
44,Utah,30492,5184878,7513.0,5067546,31552,0.0,433,427,12981,939380.0,3528,11278730.0
45,Vermont,1632,54727,1115.0,0,7795,0.0,491,203,0,35616.0,1710,103289.0
46,Virginia,27451,1882467,22266.0,0,4589,361053.0,7866,2498,0,290736.0,3656,2602582.0
47,Washington,33690,1738150,13599.0,161713,47249,488025.0,12311,1514,2546,563023.0,27248,3089068.0
48,West Virginia,3023,52693,4220.0,0,4951,0.0,2406,281,0,261376.0,4408,333358.0
49,Wisconsin,54938,5042258,13939.0,0,255266,317754.0,11221,2072,0,647173.0,2286,6346907.0
50,Wyoming,7232,5727224,1550.0,5406407,1653856,0.0,503,50,1373,1070078.0,4445,13872718.0

In [22]:
df2 = pd.read_csv(import_2)
df2=df2.rename(columns={'Total Energy Consumed 2017 (10^6 btu/capita)':'Energy_Consumed_BTU'})
df2.head()

   State_Name  State Population 2017  Energy_Consumed_BTU  Energy_Consumed_GWh
0     Alabama                4874486                  390         5.571426e+05
1     Arizona                7044008                  209         4.314585e+05
2    Arkansas                3001345                  822         7.230373e+05
3    Arkansas                3001345                  352         3.096218e+05
4  California               39358497                  200         2.306967e+06

In [15]:
rds_connection_string = f'{username}:{password}@localhost:5433/etl_db'
engine = create_engine(f'postgresql://{rds_connection_string}')

In [ ]:
engine.table_names()

In [45]:
energydf.to_sql(name='state_renewable', con=engine, if_exists='append', index=False)

In [24]:
df2.to_sql(name='state_consumption', con=engine, if_exists='append', index=False)

In [ ]:
pd.read_sql_query('select * from state_', con=engine).head()